---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/pylint.git
    rev: v3.2.5
    hooks:
      - id: pylint
        name: pylint
        language_version: python3
        additional_dependencies:
          - typing_extensions
        args:
          - --load-plugins=pylint.extensions.redefined_variable_type,pylint.extensions.bad_builtin
          - --disable=import-error
  - repo: https://github.com/google/yamlfmt
    rev: v0.13.0
    hooks:
      - id: yamlfmt
        args:
          - -conf
          - .yamlfmt
